stages:
  - test
  - staging

composer-test:
  stage: test
  image: 
    name: linuxserver/docker-compose
    # entrypoint: ["/bin/bash", "-c"]
  tags: ["docker"]
  before_script:
    - apt update && apt install gettext curl -y
  script:
    - docker-compose up -d
    - sleep 30
    - docker ps
    - ss -tulpan | grep 9200
    - docker logs elasticsearch
    - curl http://localhost:9200/_cat/health
    - docker logs elasticsearch
    
staging:
  stage: staging
  tags: ["docker"]
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
      - rsync -e "ssh -o StrictHostKeyChecking=no" -rltoDv --delete --force . root@$QA_SERVER:/root/recountanalitics
      - ssh root@$QA_SERVER "cd /root/recountanalitics && docker-compose down && docker-compose up -d"
  environment:     
    name: staging
