staging:
  stage: staging
  tags: ["docker"]
  image: alpine
  before_script:
    - apk add openssh-client rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
      - rsync -e "ssh -o StrictHostKeyChecking=no" -rltoDv --delete --force . root@$QA_SERVER:/root/recountanalitics
      - ssh -o StrictHostKeyChecking=no root@$QA_SERVER "cd /root/recountanalitics && docker-compose down && docker-compose up -d"
  environment:     
    name: staging
